[package]
name = "wcrs"
version = "0.1.0"
edition = "2021"
description = "Word counter, an UNIX-analogue for wc, written in Rust."



[dependencies]
clap = { version = "4.5.19", features = ["derive"] }